version: "3"
services:
  app:
    container_name: "teste"
    build: .
    links:
      - tad 
      - pubsub
    ports:
      - 5000:5000
  tad:
    image: postgres:9.6
    container_name: "postgres"
    environment:
      - POSTGRES_DB=tadpgweb
      - POSTGRES_USER=postgres
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
  pubsub:
    image: bigtruedata/gcloud-pubsub-emulator
    container_name: pubsub
    ports:
      - 8539:8539
